/*==============================================================
                 CUSTOMER ANALYTICS

Description : Analyze customer purchasing behavior, lifetime
              value, purchase frequency and customer
              segmentation using RFM analysis.

==============================================================*/



/*==============================================================
CUSTOMER PURCHASE FREQUENCY

Objective:
Analyze customer purchasing behavior by identifying the
distribution of one-time and repeat customers across the
marketplace.

==============================================================*/


WITH customer_orders AS
(
    SELECT
        customer_unique_id,
        COUNT(*) AS total_orders
    FROM vw_order_summary
    GROUP BY customer_unique_id
)

SELECT
    total_orders,
    COUNT(*) AS customer_count
FROM customer_orders
GROUP BY total_orders
ORDER BY total_orders;



/*==============================================================
ONE-TIME VS REPEAT CUSTOMERS

Objective:
Compare one-time and repeat customers based on customer
count, order volume, revenue and average customer value.

==============================================================*/

WITH customer_summary AS
(
    SELECT
        customer_unique_id,
        COUNT(*) AS total_orders,
        SUM(order_value) AS total_revenue
    FROM vw_order_summary
    GROUP BY customer_unique_id
),

customer_segments AS
(
    SELECT
        CASE
            WHEN total_orders = 1 THEN 'One-Time Customer'
            ELSE 'Repeat Customer'
        END AS customer_type,

        total_orders,
        total_revenue
    FROM customer_summary
)

SELECT
    customer_type,

    COUNT(*) AS customer_count,

    ROUND(
        COUNT(*) * 100.0 /
        SUM(COUNT(*)) OVER (),
        2
    ) AS customer_percentage,

    SUM(total_orders) AS total_orders,

    SUM(total_revenue) AS total_revenue,

    ROUND(
        SUM(total_revenue) * 1.0 /
        SUM(total_orders),
        2
    ) AS average_order_value,

    ROUND(
        SUM(total_revenue) * 1.0 /
        COUNT(*),
        2
    ) AS average_customer_value

FROM customer_segments

GROUP BY customer_type

ORDER BY customer_count DESC;



/*==============================================================
CUSTOMER LIFETIME VALUE (CLV)

Objective:
Measure the total revenue generated by each customer to
identify the marketplace's highest-value customers.

==============================================================*/

SELECT
    customer_unique_id,

    COUNT(*) AS total_orders,

    SUM(order_value) AS customer_lifetime_value,

    ROUND
    (
        AVG(order_value),
        2
    ) AS average_order_value,

    RANK() OVER
    (
        ORDER BY SUM(order_value) DESC
    ) AS customer_rank

FROM vw_order_summary

GROUP BY customer_unique_id

ORDER BY customer_lifetime_value DESC;



/*==============================================================
REPEAT PURCHASE GAP

Objective:
Measure the average time between consecutive purchases to
understand repeat customer purchasing behavior.

==============================================================*/

WITH customer_orders AS
(
    SELECT
        customer_unique_id,
        order_purchase_timestamp,

        LAG(order_purchase_timestamp) OVER
        (
            PARTITION BY customer_unique_id
            ORDER BY order_purchase_timestamp
        ) AS previous_purchase_date

    FROM vw_order_summary
),

purchase_gap AS
(
    SELECT
        DATEDIFF
        (
            DAY,
            previous_purchase_date,
            order_purchase_timestamp
        ) AS days_between_orders

    FROM customer_orders

    WHERE previous_purchase_date IS NOT NULL
)

SELECT

    COUNT(*) AS repeat_purchases,

    ROUND
    (
        AVG(days_between_orders),
        2
    ) AS average_days_between_orders,

    MIN(days_between_orders) AS minimum_gap_days,

    MAX(days_between_orders) AS maximum_gap_days

FROM purchase_gap;



/*==============================================================
RFM SEGMENTATION

Objective:
Segment customers using Recency, Frequency and Monetary
(RFM) metrics to identify high-value, loyal and at-risk
customer groups.

==============================================================*/

WITH customer_rfm AS
(
    SELECT
        customer_unique_id,

        DATEDIFF
        (
            DAY,
            MAX(order_purchase_timestamp),
            (SELECT MAX(order_purchase_timestamp)
             FROM vw_order_summary)
        ) AS recency,

        COUNT(*) AS frequency,

        SUM(order_value) AS monetary

    FROM vw_order_summary

    GROUP BY customer_unique_id
),

rfm_scores AS
(
    SELECT
        customer_unique_id,

        NTILE(5) OVER
        (
            ORDER BY recency ASC
        ) AS recency_score,

        CASE
            WHEN frequency = 1 THEN 1
            WHEN frequency = 2 THEN 2
            WHEN frequency = 3 THEN 3
            WHEN frequency BETWEEN 4 AND 5 THEN 4
            ELSE 5
        END AS frequency_score,

        NTILE(5) OVER
        (
            ORDER BY monetary DESC
        ) AS monetary_score

    FROM customer_rfm
),

customer_segments AS
(
    SELECT

        CASE

            -- Recent + High Frequency
            WHEN recency_score >= 4
             AND frequency_score >= 3
                THEN 'Champions'

            -- Recent + Good Spending
            WHEN recency_score >= 3
             AND monetary_score >= 4
                THEN 'Loyal Customers'

            -- Recent but Low Frequency
            WHEN recency_score >= 4
             AND frequency_score <= 2
                THEN 'Potential Loyalists'

            -- Not Recent + High Value Customer
            WHEN recency_score <= 2
             AND (frequency_score >= 3
                  OR monetary_score >= 4)
                THEN 'At Risk'

            ELSE 'Need Attention'

        END AS customer_segment

    FROM rfm_scores
)

SELECT

    customer_segment,

    COUNT(*) AS total_customers,

    ROUND
    (
        COUNT(*) * 100.0 /
        SUM(COUNT(*)) OVER (),
        2
    ) AS customer_percentage

FROM customer_segments

GROUP BY customer_segment

ORDER BY total_customers DESC;